"""把 ops[] 编译成一段 Lua 程序（spec §6.2）。"""

import json
from pathlib import Path

from pydantic import BaseModel

from src.v2.registry import OpSpec

RESULT_MARKER = "__MCP_JSON__"


def lua_string(s: str) -> str:
    out = ['"']
    for ch in s:
        code = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif code < 32 or code == 127:
            out.append(f"\\{code}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def lua_value(v) -> str:
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        if v != v or v in (float("inf"), float("-inf")):
            raise ValueError(f"cannot serialize non-finite number: {v}")
        return repr(v)
    if isinstance(v, str):
        return lua_string(v)
    if isinstance(v, (list, tuple)):
        return "{" + ",".join(lua_value(x) for x in v) + "}"
    if isinstance(v, dict):
        parts = []
        for k, val in v.items():
            if isinstance(k, str) and k.isidentifier():
                parts.append(f"{k}={lua_value(val)}")
            else:
                parts.append(f"[{lua_value(k)}]={lua_value(val)}")
        return "{" + ",".join(parts) + "}"
    raise TypeError(f"cannot serialize {type(v)!r}")


def _op_literal(spec: OpSpec, params: BaseModel) -> str:
    return lua_value(params.model_dump(mode="json"))


_HEADER = """-- generated by aseprite-mcp v2; do not edit
if not _G._mcp_common_loaded then
  dofile({common})
end
{categories}local _file = {file}
local _results = {{}}
local _sprite = nil
local function _resolve()
  if _sprite then return _sprite end
  _sprite = _G._mcp_get_sprite(_file)
  if not _sprite then _sprite = _G._mcp_created_sprite end
  if not _sprite then error("no sprite. Call create_sprite first.") end
  return _sprite
end
local function _record(name, ok, data)
  _results[#_results + 1] = {{op=name, ok=ok, data=data}}
  return ok
end
"""

_BOOTSTRAP_OPS = {"create_sprite", "open_sprite"}

_FOOTER = """if _saved_ok then
  _mcp_maybe_save(_sprite, _file)
end
print("\\n{marker}" .. json.encode({{ops=_results, saved=_saved_ok and true or false, error=_run_error}}))
"""


def compile_ops(
    parsed: list[tuple[OpSpec, BaseModel]],
    *,
    file_path: Path,
    scripts_dir: Path,
    atomic: bool,
) -> str:
    categories = sorted({spec.category for spec, _ in parsed if spec.lua})
    cat_lines = "".join(
        f"dofile({lua_string(str(scripts_dir / ('ops_' + cat + '.lua')))})\n"
        for cat in categories
    )
    header = _HEADER.format(
        common=lua_string(str(scripts_dir / "mcp_common.lua")),
        categories=cat_lines,
        file=lua_string(str(file_path)),
        marker=RESULT_MARKER,
    )

    calls = []
    for i, (spec, params) in enumerate(parsed, start=1):
        if spec.lua is None:
            continue  # 元 op（如 close_session）由 Python 侧处理，不生成 Lua
        target = "_resolve()"
        after = ""
        if i == 1 and spec.name in _BOOTSTRAP_OPS:
            target = "nil"
            after = "\n  _sprite = _G._mcp_created_sprite"
        calls.append(
            f"""do
  local _ok, _data = pcall({spec.lua}, {target}, {_op_literal(spec, params)})
  _record({lua_string(spec.name)}, _ok, _data){after}
  if not _ok then _saved_ok = false; _run_error = tostring(_data)"""
        )
        if atomic:
            calls.append(f'    error("MCP_OP_FAILED:{i}", 0)')
        calls.append("  end\nend\n")

    body = "".join(calls)

    if atomic:
        runner = f"""local _saved_ok = true
local _run_error = nil
local _tx_ok, _tx_err = pcall(function()
  app.transaction("MCP: {len(parsed)} ops", function()
{body}  end)
end)
if not _tx_ok then _saved_ok = false; _run_error = tostring(_tx_err) end
"""
    else:
        runner = f"""local _saved_ok = true
local _run_error = nil
{body}"""

    return header + runner + _FOOTER.format(marker=RESULT_MARKER)


def parse_result_stdout(stdout: str) -> dict:
    idx = stdout.rfind(RESULT_MARKER)
    if idx == -1:
        raise ValueError(f"no {RESULT_MARKER} marker in output: {stdout!r}")
    return json.loads(stdout[idx + len(RESULT_MARKER):])
